#!/bin/bash

set -eo pipefail

case "${1}" in
    remove|deconfigure  )
        if systemctl is-active --quiet ddns.service ; then
            systemctl disable --now ddns.service
        fi
        if test -f /etc/ddns/ddns.ipv4 ; then rm -v /etc/ddns/ddns.ipv4 ; fi

        # Make sure the user is removed
        if getent passwd ddns >/dev/null ; then
            userdel ddns
        fi
    ;;
    upgrade|configure   )   ;;
    failed-upgrade|abort-install|abort-remove|abort-upgrade|disappear) ;;
    *)
        echo "prerm called with unknown argument: $1" >&2
        exit 1
    ;;
esac
