#!/bin/bash

set -eo pipefail

case "${1}" in
    remove|upgrade|deconfigure  )
        if systemctl is-active --quiet ddns.service ; then systemctl disable --now ddns.service ; fi
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear) ;;
    *)
        echo "prerm called with unknown argument: $1" >&2
        exit 1
    ;;
esac
