#!/bin/bash

set -eo pipefail

case "${1}" in
    configure|upgrade|reinstall|install     )
        mv /etc/ddnsd.conf /etc/ddnsd.conf.bak || true
    ;;
    *                               )
        echo "postinst called with unknown argument: $1" >&2 ; exit 1
    ;;
esac
