#!/bin/env bash

set -eo pipefail

# Create md5sums file
find "${BUILD_PATH}" -type f -exec md5sum {} + > "${BUILD_PATH}/DEBIAN/md5sums"

# Remove BUILD_PATH for md5sums
sed -i "s|${BUILD_PATH}/||g" "${BUILD_PATH}/DEBIAN/md5sums"

# If rebuilding without cleaning, remove the line with the deb file
test ! -f "${BUILD_PATH}/DEBIAN/md5sums" || sed -i "/${APP_NAME}_${VERSION}_${AARCH}.deb/d" "${BUILD_PATH}/DEBIAN/md5sums"

# The DEBIAN directory should not be included in the md5sums file
test ! -f "${BUILD_PATH}/DEBIAN/md5sums" || sed -i "/DEBIAN\//d" "${BUILD_PATH}/DEBIAN/md5sums"
