#!/bin/env bash

set -eo pipefail

# Create md5sums file
find "${BUILD_PATH}" -type f -exec md5sum {} + > "${BUILD_PATH}/DEBIAN/md5sums"

# Remove BUILD_PATH for md5sums
sed -i "s|${BUILD_PATH}/||g" "${BUILD_PATH}/DEBIAN/md5sums"

# If rebuilding without cleaning, remove the line with the deb file
test ! -f "${BUILD_PATH}/DEBIAN/md5sums" || sed -i "/${APP_NAME}_${VERSION}_${AARCH}.deb/d" "${BUILD_PATH}/DEBIAN/md5sums"

# The DEBIAN directory should not be included in the md5sums file
test ! -f "${BUILD_PATH}/DEBIAN/md5sums" || sed -i "/DEBIAN\//d" "${BUILD_PATH}/DEBIAN/md5sums"

# Create control file
cat <<EOF > "${BUILD_PATH}/DEBIAN/control"
Package: ${APP_NAME}
Version: ${VERSION}
Section: utils
Priority: ${PRIORITY}
Architecture: all
Depends: curl, jq
Maintainer: ${MAINTAINER}
Description: ${DESCRIPTION}
  Update your dynamic DNS for your domain on Cloudflare or DuckDNS.
EOF

# Create prerm file to disable the ddns.timer if it is active
cat <<EOF > "${BUILD_PATH}/DEBIAN/prerm"
#!/bin/sh
set -e

case "\${1}" in
    remove)
        if systemctl is-active --quiet ddns.timer ; then
            systemctl disable --now ddns.timer
        fi
    ;;
    *)
        echo "prerm called with unknown argument: $1" >&2
        exit 1
    ;;
esac

exit 0
EOF

chmod 755 "${BUILD_PATH}/DEBIAN/prerm"
